create table grade (
    id binary(255) GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1) not null,
    created timestamp,
    description varchar(255),
    grade double not null,
    wage double not null,
    student_id binary(255),
    subject_id bigint,
    primary key (id)
);

create table student (
    id binary(255) GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1) not null,
    birthday date,
    name varchar(255),
    removed boolean not null,
    second_name varchar(255),
    surname varchar(255),
    primary key (id)
);

create table subject (
    id bigint GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1) not null,
    created timestamp,
    name varchar(255),
    range varchar(255),
    removed boolean not null,
    updated timestamp,
    primary key (id)
);

create table subject_students (
    subjects_id bigint not null,
    students_id binary(255) not null
);

alter table grade 
    add constraint FK5secqnjjwgh9wxk4h1xwgj1n0 
    foreign key (student_id) 
    references student;
    
alter table grade 
    add constraint FKhhw6hbmiyabjlm1jghr00m5d8 
    foreign key (subject_id) 
    references subject;

alter table subject_students 
    add constraint FKshgoyyumnrcs5ymtdukfcuul3 
    foreign key (students_id) 
    references student;

alter table subject_students 
    add constraint FKkrdmpwnc5f3wbcbhrt308vt9y 
    foreign key (subjects_id) 
    references subject;