package repository;

import domain.ClassEntity;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

public class ClassRepository implements IRepository<ClassEntity, Integer> {

    // TODO: This stuff should be stored somewhere else. (Leave it here for now)
    private static final String DB_CONNECTION_URL = "jdbc:hsqldb:hsql://localhost:9001/hsqldb;user=sa;password=sa";

    private static final String CREATE_TABLE_QUERY = "CREATE TABLE Class " +
            "(" +
            "id INTEGER GENERATED BY DEFAULT AS IDENTITY, " +
            "presidentId INTEGER, " + // TODO: Try to use it as Foreign key
            "startDate Date, " +
            "endDate Date, " +
            "profile VARCHAR(64), " +
            "special BOOLEAN" +
            ");";

    private static final String DROP_TABLE_QUERY = "DROP TABLE Public.Class";

    // TODO: (useless tho) use specific fields instead of '*'
    private static final String SELECT_QUERY = "SELECT * FROM PUBLIC.Class WHERE id = ?";

    private static final String SELECT_ALL_QUERY = "SELECT * FROM PUBLIC.Class";

    private static final String INSERT_QUERY = "INSERT INTO PUBLIC.Class(presidentId, startDate, endDate, profile, special) " +
            "VALUES(?, ?, ?, ?, ?)";

    private static final String UPDATE_QUERY = "UPDATE PUBLIC.Class SET presidentId = ?, startDate = ?, endDate = ?, " +
            "profile = ?, special = ? WHERE id = ?";

    private static final String DELETE_QUERY = "DELETE FROM PUBLIC.Class WHERE id = ?";

    private Connection connection;
    private Statement statement;

    public ClassRepository(Connection connection) {
        // Set up connection (Create table if needed)

        try {
            if (connection == null) {
                this.connection = DriverManager.getConnection(DB_CONNECTION_URL);
                this.statement = this.connection.createStatement();
            } else {
                this.connection = connection;
                this.statement = this.connection.createStatement();
            }

            ResultSet rs = this.connection.getMetaData().getTables(null, null, null, null);

            boolean tableExists = false;

            while (rs.next()) {
                if ("Class".equalsIgnoreCase(rs.getString("TABLE_NAME"))) {
                    tableExists = true;
                    break;
                }
            }

            if (!tableExists) {
                this.statement.executeUpdate(CREATE_TABLE_QUERY);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public Connection getConnection() {
        // Just to use transactions later (I hope so...)

        return this.connection;
    }

    public boolean create(ClassEntity classEntity) {
        try {
            PreparedStatement preparedStatement = setUpStatement(classEntity, INSERT_QUERY);
            preparedStatement.execute();

            return true;
        } catch (SQLException e) {
            e.printStackTrace();
            return false;
        }
    }

    public ClassEntity readByKey(Integer integer) {
        ClassEntity classEntity = null;

        try {
            PreparedStatement preparedStatement = this.connection.prepareStatement(SELECT_QUERY);
            preparedStatement.setInt(1, integer);

            ResultSet result = preparedStatement.executeQuery();

            if (result.next()) {
                classEntity = setUpClass(result);
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }

        return classEntity;
    }

    public List<ClassEntity> readAll() {
        List<ClassEntity> readResult = new ArrayList<ClassEntity>();

        try {
            ResultSet result = this.statement.executeQuery(SELECT_ALL_QUERY);

            while (result.next()) {
                readResult.add(setUpClass(result));
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }

        return readResult;
    }

    public boolean update(Integer id, ClassEntity classEntity) {
        try {
            this.connection.setAutoCommit(false);

            PreparedStatement preparedStatement = setUpStatement(classEntity, UPDATE_QUERY);
            preparedStatement.setInt(6, id);
            preparedStatement.execute();

            this.connection.commit();

            return true;
        } catch (SQLException e) {
            e.printStackTrace();
            return false;
        }
    }

    public boolean delete(Integer id) {
        try {
            this.connection.setAutoCommit(false);

            PreparedStatement preparedStatement = this.connection.prepareStatement(DELETE_QUERY);
            preparedStatement.setInt(1, id);
            preparedStatement.execute();

            this.connection.commit();

            return true;
        } catch (SQLException e) {
            e.printStackTrace();
            return false;
        }
    }

    public void drop() {
        try {
            PreparedStatement preparedStatement = connection.prepareStatement(DROP_TABLE_QUERY);
            preparedStatement.execute();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private ClassEntity setUpClass(ResultSet result) throws SQLException {
        ClassEntity classEntity = new ClassEntity();

        classEntity.setId(result.getInt(1));
        classEntity.setPresidentId(result.getInt(2));
        classEntity.setStartDate(result.getDate(3));
        classEntity.setEndDate(result.getDate(4));
        classEntity.setProfile(result.getString(5));
        classEntity.setSpecial(result.getBoolean(6));

        return classEntity;
    }

    private PreparedStatement setUpStatement(ClassEntity classEntity, String query) throws SQLException {
        PreparedStatement preparedStatement = this.connection.prepareStatement(query);

        preparedStatement.setInt(1, classEntity.getPresidentId() == null ? -1 : classEntity.getPresidentId());
        preparedStatement.setDate(2, classEntity.getStartDate());
        preparedStatement.setDate(3, classEntity.getEndDate());
        preparedStatement.setString(4, classEntity.getProfile());
        preparedStatement.setBoolean(5, classEntity.isSpecial());

        return preparedStatement;
    }
}
