package repository;

import domain.StudentEntity;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

public class StudentRepository implements IRepository<StudentEntity, Integer> {

    // TODO: Same as the ClassRepository
    private static final String DB_CONNECTION_URL = "jdbc:hsqldb:hsql://localhost:9001/hsqldb;user=sa;password=sa";

    private static final String CREATE_TABLE_QUERY = "CREATE TABLE Student " +
            "(" +
            "id INTEGER GENERATED BY DEFAULT AS IDENTITY, " +
            "classId INTEGER, " +
            "name VARCHAR(64), " +
            "secondName VARCHAR(64), " +
            "surname VARCHAR(64), " +
            "parentNames VARCHAR(64), " +
            "phoneNumber VARCHAR(64), " +
            "birthDate Date, " +
            "pesel VARCHAR(64), " +
            "street VARCHAR(64), " +
            "houseNumber VARCHAR(64), " +
            ");";

    private static final String DROP_TABLE_QUERY = "DROP TABLE Public.Student";

    // TODO: (useless tho) use specific fields instead of '*'
    private static final String SELECT_QUERY = "SELECT * FROM PUBLIC.Student WHERE id = ?";

    private static final String SELECT_ALL_QUERY = "SELECT * FROM PUBLIC.Student";

    private static final String INSERT_QUERY = "INSERT INTO PUBLIC.Student(classId, name, secondName, surname, parentNames, phoneNumber, birthDate, pesel, street, houseNumber) " +
            "VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

    private static final String UPDATE_QUERY = "UPDATE PUBLIC.Student SET classId = ?, name = ?, secondName = ?, " +
            "surname = ?, parentNames = ?, phoneNumber = ?, birthDate = ?, pesel = ?, street = ?, houseNumber = ?  " +
            "WHERE id = ?";

    private static final String DELETE_QUERY = "DELETE FROM PUBLIC.Student WHERE id = ?";

    private Connection connection;
    private Statement statement;

    public StudentRepository(Connection connection) {
        // Set up connection (Create table if needed)

        try {
            if (connection == null) {
                this.connection = DriverManager.getConnection(DB_CONNECTION_URL);
                this.statement = this.connection.createStatement();
            } else {
                this.connection = connection;
                this.statement = this.connection.createStatement();
            }

            ResultSet rs = this.connection.getMetaData().getTables(null, null, null, null);

            boolean tableExists = false;

            while (rs.next()) {
                if ("Student".equalsIgnoreCase(rs.getString("TABLE_NAME"))) {
                    tableExists = true;
                    break;
                }
            }

            if (!tableExists) {
                this.statement.executeUpdate(CREATE_TABLE_QUERY);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public Connection getConnection() {
        // Just to use transactions later (I hope so...)

        return this.connection;
    }

    public boolean create(StudentEntity student) {
        try {
            PreparedStatement preparedStatement = setUpStatement(student, INSERT_QUERY);
            preparedStatement.execute();

            return true;
        } catch (SQLException e) {
            e.printStackTrace();
            return false;
        }
    }

    public StudentEntity readByKey(Integer integer) {
        StudentEntity student = null;

        try {
            PreparedStatement preparedStatement = this.connection.prepareStatement(SELECT_QUERY);
            preparedStatement.setInt(1, integer);

            ResultSet result = preparedStatement.executeQuery();

            if (result.next()) {
                student = setUpStudent(result);
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }

        return student;
    }

    public List<StudentEntity> readAll() {
        List<StudentEntity> readResult = new ArrayList<StudentEntity>();

        try {
            ResultSet result = this.statement.executeQuery(SELECT_ALL_QUERY);

            while (result.next()) {
                readResult.add(setUpStudent(result));
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }

        return readResult;
    }

    public boolean update(Integer id, StudentEntity student) {
        try {
            this.connection.setAutoCommit(false);

            PreparedStatement preparedStatement = setUpStatement(student, UPDATE_QUERY);
            preparedStatement.setInt(11, id);
            preparedStatement.execute();

            this.connection.commit();

            return true;
        } catch (SQLException e) {
            e.printStackTrace();
            return false;
        }
    }

    public boolean delete(Integer id) {
        try {
            PreparedStatement preparedStatement = this.connection.prepareStatement(DELETE_QUERY);
            preparedStatement.setInt(1, id);
            preparedStatement.execute();

            return true;
        } catch (SQLException e) {
            e.printStackTrace();
            return false;
        }
    }

    public void drop() {
        try {
            PreparedStatement preparedStatement = connection.prepareStatement(DROP_TABLE_QUERY);
            preparedStatement.execute();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private StudentEntity setUpStudent(ResultSet result) throws SQLException {
        StudentEntity student = new StudentEntity();

        student.setId(result.getInt(1));
        student.setClassId(result.getInt(2));
        student.setName(result.getString(3));
        student.setSecondName(result.getString(4));
        student.setSurname(result.getString(5));
        student.setParentNames(result.getString(6));
        student.setPhoneNumber(result.getString(7));
        student.setBirthDate(result.getDate(8));
        student.setPesel(result.getString(9));
        student.setStreet(result.getString(10));
        student.setHouseNumber(result.getString(11));

        return student;
    }

    private PreparedStatement setUpStatement(StudentEntity student, String query) throws SQLException {
        PreparedStatement preparedStatement = this.connection.prepareStatement(query);

        preparedStatement.setInt(1, student.getClassId());
        preparedStatement.setString(2, student.getName());
        preparedStatement.setString(3, student.getSecondName());
        preparedStatement.setString(4, student.getSurname());
        preparedStatement.setString(5, student.getParentNames());
        preparedStatement.setString(6, student.getPhoneNumber());
        preparedStatement.setDate(7, student.getBirthDate());
        preparedStatement.setString(8, student.getPesel());
        preparedStatement.setString(9, student.getStreet());
        preparedStatement.setString(10, student.getHouseNumber());

        return preparedStatement;
    }
}
