package services;

import domain.Szachy;

import java.sql.*;

public class SzachyService implements ISzachyService{

    private final String DB_URL = "jdbc:hsqldb:hsql://localhost/workdb";

    private final String CREATE_TABLE_PERSON = "CREATE TABLE Szachy\n" +
                                               "(\n" +
                                               "id INTEGER GENERATED BY DEFAULT AS IDENTITY,\n" +
                                               "nazwa VARCHAR(64),\n" +
                                               "gracz VARCHAR(32),\n" +
                                               "stanowisko INTEGER\n" +
                                               ")";

    private final String SELECT_QUERY = "SELECT id, nazwa, gracz, stanowisko FROM Szachy";
    private final String INSERT_QUERY = "INSERT INTO Szachy(nazwa, gracz, stanowisko) VALUES(?, ?, ?)";
    private final String UPDATE_QUERY = "UPDATE Szachy SET nazwa = ?, gracz = ?, stanowisko = ? WHERE id = ?";
    private final String DELETE_QUERY = "DELETE FROM Szachy WHERE id = ?";


    private Connection connection;
    private Statement statement;

    public SzachyService(){

        try {
            connection = DriverManager.getConnection(DB_URL);

//            System.out.println("Connected");

            statement = connection.createStatement();

            ResultSet rs = connection.getMetaData().getTables(null, null, null, null);

            boolean tableExists = false;

            while (rs.next()) {
                if ("Szachy".equalsIgnoreCase(rs.getString("TABLE_NAME"))) {
                    tableExists = true;
                    break;
                }
            }

            if (!tableExists) {
                statement.executeUpdate(CREATE_TABLE_PERSON);
            }

        } catch(SQLException e){
            System.out.println(":(");
            e.printStackTrace();
        }

    }

    public void create(Szachy szachy) {

        try {
            PreparedStatement preparedStatement = connection.prepareStatement(INSERT_QUERY);

            preparedStatement.setString(1, szachy.getNazwa());
            preparedStatement.setString(2, szachy.getGracz());
            preparedStatement.setInt(3, szachy.getStanowisko());

            preparedStatement.execute();

        } catch(SQLException e){
            System.out.println("Create Exception");
//            e.printStackTrace();
        }

    }

    public void read(){

        try {
            ResultSet result = statement.executeQuery(SELECT_QUERY);

            while(result.next()){

                Szachy szachy = new Szachy(result.getInt(1), result.getString(2), result.getString(3), result.getInt(4));

                System.out.println(szachy);
            }

        } catch(SQLException e){
            System.out.println("Read Exception");
//            e.printStackTrace();
        }

    }

    public void update(int id, Szachy szachy) {

        try {
            PreparedStatement preparedStatement = connection.prepareStatement(UPDATE_QUERY);

            preparedStatement.setString(1, szachy.getNazwa());
            preparedStatement.setString(2, szachy.getGracz());
            preparedStatement.setInt(3, szachy.getStanowisko());
            preparedStatement.setInt(4, id);

            preparedStatement.execute();

        } catch(SQLException e){
            System.out.println("Update Exception");
//            e.printStackTrace();
        }

    }

    public void delete(int id) {

        try {
            PreparedStatement preparedStatement = connection.prepareStatement(DELETE_QUERY);

            preparedStatement.setInt(1, id);

            preparedStatement.execute();

        } catch(SQLException e){
            System.out.println("Delete Exception");
//            e.printStackTrace();
        }

    }


}
